language: python
sudo: false
python:
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"
 - "pypy"

install:
 - "pip install -r requirements.txt"

script:
 - "cookiecutter --no-input ."
 - "cd pypt"
 - "py.test tests/"

notifications:
  email:
    on_success: always
    on_failure: always
